### ISSUE TITLE
Elapsed time is always 0 when using lyra in cloudflare workers

### ISSUE THREAD

**Issue by ShivamJoker** [LyraSearch/lyra#129]
**Describe the bug**

**To Reproduce**
1. Create a simple DB
2. Insert some items
3. Do a simple search
4. Deploy to Cloudflare workers (can be used with astro as well)
5. Log the elapsed time from result

Here is the sample repo made with astro - https://github.com/ShivamJoker/Dad-jokes-SSR/blob/main/src/pages/index.astro#L25

Here is the live website - https://dad-jokes-ssr.pages.dev/?q=ice

**Expected behavior**
It should show the actual time instead of 0

**Screenshots**
![image](https://user-images.githubusercontent.com/23727670/189291495-313a890d-393b-4ba0-9180-06471d977148.png)

**Additional context**
I am using astro with SSR on cloudflare workers and using the latest lyra version

**Comment by micheleriva** [comment]
Hi @ShivamJoker,
this might be due to a momentary workaround we had to take when serializing to JSON. Lyra uses a `BigInt` data type to express the elapsed time in nanoseconds, and `BigInt` cannot be serialized to JSON.

We're well aware of this little problem, and we have already planned a solution. I don't have any estimation to share, I hope this is not a blocker for your project.

**Comment by ShivamJoker** [comment]
Oh that's great if you already know, I just wanted to inform you about the bug.

No it's not a blocker.

**Comment by micheleriva** [comment]
Good to hear, thanks!

**Comment by abhay187** [comment]
Hey, @micheleriva This problem still exists even with `formatNanoseconds(searchResult.elapsed)` function from the library. Can you update us that the issue is fixed or not? Also, a working solution will be helpful if possible.
